using System.Collections.Generic;
using System.Linq;
using JetBrains.Metadata.Reader.API;
using JetBrains.Metadata.Reader.Impl;
using JetBrains.ProjectModel;
using JetBrains.ReSharper.Psi;
using JetBrains.ReSharper.Psi.Caches;

namespace ReSharperPlugin.SharedMeta
{
    /// <summary>
    /// Maps between a user-authored <c>[MetaMethod]</c> on a <c>[MetaService]</c>
    /// interface and every method generated for it by SharedMeta.Generator.
    /// <para>
    /// Since SharedMeta 0.16.0 every generated method carries
    /// <c>[GeneratedFromMetaMethod(typeof(IFoo), "Bar")]</c>, so the matcher does
    /// purely attribute-driven lookup — no naming-convention guessing, no namespace
    /// prediction, no class-name parsing. This is what lets us cover all five
    /// generated layouts in one place: <c>*ApiClient</c>, <c>*EntityQueryApi</c>,
    /// <c>{I}EntityCaller</c>, <c>*EntityRecorder</c>, <c>*LocalEntityCaller</c>,
    /// <c>*EntityReplayer</c>. Older generated code that lacks the attribute is
    /// invisible to the matcher — the user must regenerate against SharedMeta ≥ 0.16.0.
    /// </para>
    /// </summary>
    public static class MetaServiceMatcher
    {
        public const string MetaServiceAttributeFqn        = "SharedMeta.Core.MetaServiceAttribute";
        public const string MetaMethodAttributeFqn         = "SharedMeta.Core.MetaMethodAttribute";
        public const string GeneratedFromMetaMethodAttrFqn = "SharedMeta.Core.GeneratedFromMetaMethodAttribute";

        // Short name as indexed by the ReSharper AnnotatedEntities cache. Must include
        // the "Attribute" suffix — that is the cache key.
        public const string GeneratedFromMetaMethodAttrShortName = "GeneratedFromMetaMethodAttribute";

        private static readonly IClrTypeName MetaServiceAttr        = new ClrTypeName(MetaServiceAttributeFqn);
        private static readonly IClrTypeName MetaMethodAttr         = new ClrTypeName(MetaMethodAttributeFqn);
        private static readonly IClrTypeName GeneratedFromMetaAttr  = new ClrTypeName(GeneratedFromMetaMethodAttrFqn);

        // ----------------------------------------------------------------------------
        // Classification
        // ----------------------------------------------------------------------------

        public static bool IsMetaServiceInterface(ITypeElement? type)
        {
            if (type is not IInterface iface) return false;
            return iface.HasAttributeInstance(MetaServiceAttr, inherit: false);
        }

        public static bool IsMetaMethod(IMethod? method)
        {
            if (method == null) return false;
            if (!IsMetaServiceInterface(method.GetContainingType())) return false;
            return method.HasAttributeInstance(MetaMethodAttr, inherit: false);
        }

        public static bool IsGeneratedClientMethod(IMethod? method)
        {
            if (method == null) return false;
            return method.HasAttributeInstance(GeneratedFromMetaAttr, inherit: false);
        }

        // ----------------------------------------------------------------------------
        // Counterpart lookup (attribute-driven)
        // ----------------------------------------------------------------------------

        /// <summary>
        /// Reverse direction: given a method generated by SharedMeta.Generator, returns
        /// the original <c>[MetaMethod]</c> it mirrors. Reads the
        /// <c>[GeneratedFromMetaMethod]</c> instance directly — O(1) on the method itself.
        /// </summary>
        public static IMethod? FindMetaMethodCounterpart(IMethod generatedMethod)
        {
            var (iface, methodName) = ReadGeneratedFromAttribute(generatedMethod);
            if (iface == null || methodName == null) return null;
            if (!IsMetaServiceInterface(iface)) return null;

            foreach (var candidate in iface.Methods)
            {
                if (candidate.ShortName == methodName && IsMetaMethod(candidate))
                    return candidate;
            }
            return null;
        }

        /// <summary>
        /// Forward direction: given a <c>[MetaMethod]</c>, returns every method in the
        /// solution annotated with <c>[GeneratedFromMetaMethod(typeof(thisInterface), "thisMethodName")]</c>.
        /// <para>
        /// Two-stage filter to keep this fast on a real codebase:
        /// <list type="number">
        ///   <item>Pull the set of <em>method short names</em> known to carry the attribute
        ///         from <see cref="AnnotatedMembersEx.GetMembersByAttributeName"/> (cached
        ///         solution-wide index).</item>
        ///   <item>For each such name resolve the actual elements via the symbol scope
        ///         and verify the attribute payload matches our target.</item>
        /// </list>
        /// </para>
        /// </summary>
        // Suffixes the generators append to the original interface method name. Used as
        // a where-to-look-first hint — verification is still attribute-driven so unrelated
        // methods that happen to follow this naming are filtered out.
        //   ""        — interface method already returns Task (generator preserves the name)
        //   "Async"   — default suffix on most public mirrors
        //   "Sync"    — Sync = SyncApi.Generate / OnlySync overloads
        //   "Signal"  — fire-and-forget Signal mode
        private static readonly string[] CandidateSuffixes = { "", "Async", "Sync", "Signal" };

        public static List<IMethod> FindGeneratedCounterparts(IMethod metaMethod, ISolution solution)
        {
            var result = new List<IMethod>();
            if (metaMethod.GetContainingType() is not IInterface iface)
            {
                DiagLog.Write($"FindGeneratedCounterparts SKIP: containing type is not interface ({metaMethod.GetContainingType()?.GetType().Name ?? "<null>"})");
                return result;
            }

            var ifaceClrName = iface.GetClrName();
            var metaMethodName = metaMethod.ShortName;

            DiagLog.Write($"FindGeneratedCounterparts: iface={ifaceClrName.FullName} method={metaMethodName}");

            // The ReSharper AnnotatedMembersEx index turned out to be empty for our use
            // case (it returns 0 even for [Obsolete] in some Rider configurations — likely
            // requires Solution-Wide Analysis to be enabled, which most users do not have
            // on). Fall back to a name-narrowed PSI scan: enumerate methods named
            // {OriginalName}+{suffix} and verify each one carries the correct
            // [GeneratedFromMetaMethod] attribute.
            var psiServices = metaMethod.GetPsiServices();
            var symbolScope = psiServices.Symbols.GetSymbolScope(
                LibrarySymbolScope.FULL, caseSensitive: true);

            int candidateCount = 0;
            int attrPresent = 0;
            int matched = 0;

            foreach (var suffix in CandidateSuffixes)
            {
                var candidateName = metaMethodName + suffix;
                var sourceMembers = symbolScope.GetSourceMembers(candidateName).ToList();
                var compiledMembers = symbolScope.GetCompiledMembers(candidateName).ToList();
                DiagLog.Write($"  scan name='{candidateName}': {sourceMembers.Count} source + {compiledMembers.Count} compiled members");

                foreach (var member in sourceMembers.Concat(compiledMembers))
                {
                    if (member is not IMethod candidate) continue;
                    candidateCount++;
                    var (targetIface, targetMethodName) = ReadGeneratedFromAttribute(candidate);
                    if (targetIface == null) continue;
                    attrPresent++;
                    if (targetMethodName != metaMethodName) continue;
                    var targetClrName = targetIface.GetClrName();
                    if (!ifaceClrName.Equals(targetClrName))
                    {
                        DiagLog.Write($"    MISS: {candidate.GetContainingType()?.GetClrName().FullName}.{candidate.ShortName} attr={targetClrName.FullName}/{targetMethodName}");
                        continue;
                    }
                    DiagLog.Write($"    HIT:  {candidate.GetContainingType()?.GetClrName().FullName}.{candidate.ShortName}");
                    matched++;
                    result.Add(candidate);
                }
            }

            DiagLog.Write($"  SUMMARY: candidates={candidateCount} with-attr={attrPresent} matched={matched}");
            return result;
        }

        // ----------------------------------------------------------------------------
        // Attribute reader
        // ----------------------------------------------------------------------------

        /// <summary>
        /// Returns the <c>(serviceInterface, methodName)</c> tuple from the
        /// <c>[GeneratedFromMetaMethod]</c> instance on <paramref name="method"/>,
        /// or <c>(null, null)</c> if the attribute is absent or malformed.
        /// </summary>
        private static (ITypeElement? Interface, string? MethodName) ReadGeneratedFromAttribute(IMethod method)
        {
            var attr = method.GetAttributeInstances(GeneratedFromMetaAttr, inherit: false).FirstOrDefault();
            if (attr == null) return (null, null);
            if (attr.PositionParameterCount < 2) return (null, null);

            var typeParam = attr.PositionParameter(0);
            var nameParam = attr.PositionParameter(1);

            ITypeElement? iface = null;
            if (typeParam.IsType && typeParam.TypeValue is IDeclaredType declaredType)
                iface = declaredType.GetTypeElement();

            string? methodName = null;
            if (nameParam.IsConstant && nameParam.ConstantValue.IsString())
                methodName = nameParam.ConstantValue.StringValue;

            return (iface, methodName);
        }
    }
}
